import {parseDelegation} from './delegation-parser.mjs';
import {connectorError, normalizeError, unsupported} from './http.mjs';

export function createSlackConnector({workspaceId, channelId, senderIds, credentials, transport} = {}) {
  if (!workspaceId || !channelId || !Array.isArray(senderIds) || !credentials?.get || typeof transport !== 'function') throw new TypeError('invalid Slack connector configuration');
  async function request(method, params = {}) { try { const token = await credentials.get('media.rhize.tasks.slack', 'bot-token'); const response = await transport({url: `https://slack.com/api/${method}?${new URLSearchParams(params)}`, method: 'GET', headers: {authorization: `Bearer ${token}`}}); const body = response?.body; if (response?.status < 200 || response?.status >= 300 || !body || body.ok !== true) throw connectorError(body?.error === 'ratelimited' ? 'rate_limit' : body?.error === 'invalid_auth' ? 'authorization' : 'slack_api', {retryable: body?.error === 'ratelimited' || response?.status >= 500, status: response?.status}); return response; } catch (error) { throw normalizeError(error); } }
  async function pages(method, params) { const all = []; const cursors = new Set(); let cursor = ''; for (let count = 0; count < 100; count += 1) { const body = (await request(method, {...params, cursor, limit: '100'})).body; all.push(...(body.messages ?? [])); cursor = body.response_metadata?.next_cursor ?? ''; if (!cursor) return all; if (cursors.has(cursor)) throw connectorError('pagination_loop'); cursors.add(cursor); } throw connectorError('pagination_limit'); }
  return { async health() { const body = (await request('auth.test')).body; if (body.team_id !== workspaceId) throw connectorError('authorization'); return {ok: true}; }, async discover() { return {workspaceId, channelId, senderIds: [...senderIds]}; }, async readSnapshot() { const seen = new Set(); const values = []; for (const parent of await pages('conversations.history', {channel: channelId})) { if (!parent.thread_ts) continue; const replies = await pages('conversations.replies', {channel: channelId, ts: parent.ts}); for (const reply of replies.slice(1)) { const senderId = reply.bot_id ?? reply.app_id ?? reply.user; try { const item = parseDelegation({workspaceId, channelId, senderId, text: reply.text}, {workspaceId, channelId, senderIds}); if (!seen.has(item.ingestionKey)) { seen.add(item.ingestionKey); values.push(item); } } catch {} } } return values; }, applyOperation: unsupported, findByExternalId: unsupported };
}
